CREATE DATABASE dbDEMO;
GO

USE dbDEMO;
GO

--- CREACION DE TABLAS 
--  Create table  cliente
CREATE TABLE cliente
(
IDCLI int  IDENTITY(1,1) ,
NOMCLI VARCHAR (30) NOT NULL,
APECLI VARCHAR (30) NOT NULL,
DNICLI CHAR (8) NOT NULL,
ESTCLI CHAR (1) NOT NULL,
 PRIMARY KEY (IDCLI)
);


--  Insertar datos en la tabla cliente
INSERT INTO cliente
(NOMCLI, APECLI, DNICLI, ESTCLI)
VALUES
('JUAN GABRIEL','RODRIGUEZ SANCHEZ','74143345','A'),
('CARL SIMON','SANCHEZ PEREZ','74153321','A'),
('FRANK RENATO','FELIPE CUENCA','76213421','A'),
('PETER PARKER','HUAY BLANCO','74140385', 'I'),
('HOMERO GABRIEL','SIMPSON VALDÉZ','76528534','A'),
('LUCAS PAUL','LOPEZ CUENCA','74287655','A'),
('MIGUEL BRODA', 'FALCÓN BARRIOS','74173672','A');
GO

SELECT * FROM cliente where ESTCLI = 'A' ORDER BY IDCLI DESC;